baseURL = "/"
languageCode = "ja"
title = "The Curious Engineer’s Compass"
defaultContentLanguage = "ja"
enableRobotsTXT = true
theme = "hugo-theme-stack"

# GitHub Pages 側で --baseURL を上書きします（workflow 参照）

[pagination]
  pagerSize = 10

[params]
  mainSections = ["posts"]
  description = "Hugo + Stack テーマのブログ"
  rssFullContent = true
  github_username = "mbook-x86"
  profile_comment = "毎日の開発で得た学びをシェアしていく、成長記録ノート。 エンジニアとして気になること、試してみたことを気軽に発信します。"

  [params.sidebar]
    subtitle = "技術メモと日々の記録"
    [params.sidebar.avatar]
      enabled = false
      local = false
      src = ""

  [params.widgets]
  [[params.widgets.homepage]]
    type = "categories"
    [params.widgets.homepage.params]
      limit = 10
  [[params.widgets.homepage]]
    type = "tag-cloud"
    [params.widgets.homepage.params]
      limit = 10
  [[params.widgets.page]]
    type = "toc"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[[params.social]]
  name = "GitHub"
  icon = "brand-github"
  url = "https://github.com/yourname"
[[params.social]]
  name = "X"
  icon = "brand-x"
  url = "https://x.com/yourname"
[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

# Added by Codex: GitHubプロフィール用設定とPostsメニュー
 

 
